config/routes.rb
Sonny::Application.routes.draw do
  resources :shows

  devise_for :users
  
  # home
  root :to => 'home#index'
  get 'home', :to => 'home#home_page', :as => 'home_page'
end

app/models/episode.rb
class Episode < ActiveRecord:Migration

  belongs_to :season
  belongs_to :show, :through => :season

end

app/models/season.rb
class Season < ActiveRecord::Base

  has_many :episodes
  belongs_to :show

end

app/models/show.rb
class Show < ActiveRecord::Base
  attr_accessible :description, :name, :api_id, :imdb_id

  has_many :seasons
  has_many :episodes, :through => :seasons

  validates_uniqueness_of :name, :api_id, :imdb_id

  def self.search_and_create(show_name)
  	show_data = TVAPI.search_for_show(show_name)
  	return nil if show_data.blank?
    Show.create(show_data)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :show_ids

  has_and_belongs_to_many :shows
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to home_page_path 
    else
      render :layout => 'landing_page'
    end
  end

  def home_page
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shows }
    end
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
    @show = Show.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/new
  # GET /shows/new.json
  def new
    @show = Show.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @show }
    end
  end

  # GET /shows/1/edit
  def edit
    @show = Show.find(params[:id])
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(params[:show])

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render json: @show, status: :created, location: @show }
      else
        format.html { render action: "new" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shows/1
  # PUT /shows/1.json
  def update
    @show = Show.find(params[:id])

    respond_to do |format|
      if @show.update_attributes(params[:show])
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show = Show.find(params[:id])
    @show.destroy

    respond_to do |format|
      format.html { redirect_to shows_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/home_page.html.erb
Welcome home! ;)
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

app/views/home/index.html.erb
<div class="left">
<p>What did I miss? Sonny will help!</p>
</div>
<div class="right">
	<p>
		<%= link_to "Sign up", new_user_registration_path %>
		or
		<%= link_to "Sign in", new_user_session_path %>
	</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sonny</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sonny</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "landing_page" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="wrapper">
<%= yield %>
</div>

</body>
</html>

app/views/shows/_form.html.erb
<%= form_for(@show) do |f| %>
  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@show.errors.count, "error") %> prohibited this show from being saved:</h2>

      <ul>
      <% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<h1>Editing show</h1>

<%= render 'form' %>

<%= link_to 'Show', @show %> |
<%= link_to 'Back', shows_path %>

app/views/shows/index.html.erb
<h1>Listing shows</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shows.each do |show| %>
  <tr>
    <td><%= show.name %></td>
    <td><%= show.description %></td>
    <td><%= link_to 'Show', show %></td>
    <td><%= link_to 'Edit', edit_show_path(show) %></td>
    <td><%= link_to 'Destroy', show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Show', new_show_path %>

app/views/shows/new.html.erb
<h1>New show</h1>

<%= render 'form' %>

<%= link_to 'Back', shows_path %>

app/views/shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @show.name %>
</p>

<p>
  <b>Description:</b>
  <%= @show.description %>
</p>


<%= link_to 'Edit', edit_show_path(@show) %> |
<%= link_to 'Back', shows_path %>